global:
  scrape_interval: 1s
  evaluation_interval:  1s

scrape_configs:
  - job_name: server
    static_configs:
      - targets: ['server-1.1:8000', 'server-1.2:8000']
        labels:
          deployment: 'deployment-1'
      - targets: [ 'server-2.1:8000']
        labels:
          deployment: 'deployment-2'
