{
 "title": "FastAPI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "db_addr", "label": "db_addr", "query": "${VAR_DB_ADDR}" },
   { "name": "deployment", "label": "deployment", "query": "${VAR_DEPLOYMENT}" }
  ]
 },
 "panels": [
  {
   "title": "Current variables",
   "type": "text",
   "description": "See more in settings",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "deployment=\"${deployment}\"\n\ndb_addr=\"${db_addr}\""
   }
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{deployment=\"$deployment\"})",
     "legendFormat": "Total instances"
    },
    {
     "expr": "sum(up{deployment=\"$deployment\"})",
     "legendFormat": "Active instances"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        starlette_requests_total{\n            deployment=\"$deployment\",\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(\n    rate(\n        starlette_requests_total{\n            deployment=\"$deployment\",\n            path_template!=\"/metrics\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "logic"
    },
    {
     "expr": "sum(\n    rate(\n        starlette_requests_total{\n            deployment=\"$deployment\",\n            path_template=\"/metrics\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "metrics"
    },
    {
     "expr": "sum(\n    rate(\n        starlette_exceptions_total{\n            deployment=\"$deployment\",\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "exceptions"
    },
    {
     "expr": "sum(\n    rate(\n        starlette_responses_total{\n            deployment=\"$deployment\",\n            status_code=~\"4..|5..\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99,\n    sum(\n        rate(\n            starlette_requests_processing_time_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "99-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n        rate(\n            starlette_requests_processing_time_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "95-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.90,\n    sum(\n        rate(\n            starlette_requests_processing_time_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "90-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.80,\n    sum(\n        rate(\n            starlette_requests_processing_time_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "80-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.50,\n    sum(\n        rate(\n            starlette_requests_processing_time_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "50-ый"
    }
   ]
  },
  {
   "title": "RPS by method and path_template",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        starlette_requests_total{\n            deployment=\"$deployment\",\n        }[$__rate_interval]\n    )\n) by (method, path_template)",
     "legendFormat": "{{ method }} {{ path_template }}"
    }
   ]
  },
  {
   "title": "Latency by method and path_template. Percentile 95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n        rate(\n            starlette_requests_processing_time_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le, method, path_template)\n)",
     "legendFormat": "{{ method }} {{ path_template }}"
    }
   ]
  },
  {
   "title": "Latency by method and path_template. Percentile 50",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.50,\n    sum(\n        rate(\n            starlette_requests_processing_time_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le, method, path_template)\n)",
     "legendFormat": "{{ method }} {{ path_template }}"
    }
   ]
  },
  {
   "title": "Success by method, path_template and status_code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        starlette_responses_total{\n            deployment=\"$deployment\",\n            status_code=~\"2..|3..\"\n        }[$__rate_interval]\n    )\n) by (method, path_template, status_code)",
     "legendFormat": "[{{ status_code }}] {{ method }} {{ path_template }} "
    }
   ]
  },
  {
   "title": "Errors by method, path_template and status_code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        starlette_responses_total{\n            deployment=\"$deployment\",\n            status_code=~\"4..|5..\"\n        }[$__rate_interval]\n    )\n) by (method, path_template, status_code)",
     "legendFormat": "[{{ status_code }}] {{ method }} {{ path_template }} "
    }
   ]
  },
  {
   "title": "Exceptions by method, path_template and exception_type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        starlette_exceptions_total{\n            deployment=\"$deployment\",\n        }[$__rate_interval]\n    )\n) by (method, path_template, exception_type)",
     "legendFormat": "[{{ exception_type }}] {{ method }} {{ path_template }}"
    }
   ]
  },
  {
   "title": "Response bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        starlette_responses_bytes_sum{\n            deployment=\"$deployment\",\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Response bytes per second by method and path_template",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        starlette_responses_bytes_sum{\n            deployment=\"$deployment\",\n        }[$__rate_interval]\n    )\n) by (method, path_template)",
     "legendFormat": "{{ method }} {{ path_template }} "
    }
   ]
  },
  {
   "title": "Response bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99,\n    sum(\n        rate(\n            starlette_responses_bytes_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "99-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n        rate(\n            starlette_responses_bytes_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "95-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.90,\n    sum(\n        rate(\n            starlette_responses_bytes_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "90-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.80,\n    sum(\n        rate(\n            starlette_responses_bytes_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "80-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.50,\n    sum(\n        rate(\n            starlette_responses_bytes_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "50-ый"
    }
   ]
  },
  {
   "title": "Response bytes by method and path_template. Percentile 95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n        rate(\n            starlette_responses_bytes_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le, method, path_template)\n)",
     "legendFormat": "{{ method }} {{ path_template }}"
    }
   ]
  },
  {
   "title": "Response bytes by method and path_template. Percentile 50",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.50,\n    sum(\n        rate(\n            starlette_responses_bytes_bucket{\n                deployment=\"$deployment\",\n            }[$__rate_interval]\n        )\n    ) by (le, method, path_template)\n)",
     "legendFormat": "{{ method }} {{ path_template }}"
    }
   ]
  },
  { "title": "DB ($db_addr)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        asyncpg_queries_total{\n            deployment=\"$deployment\",\n            addr=\"$db_addr\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(\n    rate(\n        asyncpg_exceptions_total{\n                deployment=\"$deployment\",\n                addr=\"$db_addr\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "exceptions"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99,\n    sum(\n        rate(\n            asyncpg_queries_processing_time_seconds_bucket{\n                deployment=\"$deployment\",\n                addr=\"$db_addr\"\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "99-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n        rate(\n            asyncpg_queries_processing_time_seconds_bucket{\n                deployment=\"$deployment\",\n                addr=\"$db_addr\"\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "95-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.90,\n    sum(\n        rate(\n            asyncpg_queries_processing_time_seconds_bucket{\n                deployment=\"$deployment\",\n                addr=\"$db_addr\"\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "90-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.80,\n    sum(\n        rate(\n            asyncpg_queries_processing_time_seconds_bucket{\n                deployment=\"$deployment\",\n                addr=\"$db_addr\"\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "80-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.50,\n    sum(\n        rate(\n            asyncpg_queries_processing_time_seconds_bucket{\n                deployment=\"$deployment\",\n                addr=\"$db_addr\"\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "50-ый"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        asyncpg_exceptions_total{\n                deployment=\"$deployment\",\n                addr=\"$db_addr\"\n        }[$__rate_interval]\n    )\n) by (exception_type)",
     "legendFormat": "{{ exception_type }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(asyncpg_connections{deployment=\"$deployment\", addr=\"$db_addr\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Rate of new connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        asyncpg_connections_new_total{\n            deployment=\"$deployment\",\n            addr=\"$db_addr\",\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(asyncpg_pool_max_size{deployment=\"$deployment\", addr=\"$db_addr\"})",
     "legendFormat": "max_size"
    },
    {
     "expr": "sum(asyncpg_pool_min_size{deployment=\"$deployment\", addr=\"$db_addr\"})",
     "legendFormat": "min_size"
    },
    {
     "expr": "sum(asyncpg_pool_idle_size{deployment=\"$deployment\", addr=\"$db_addr\"})",
     "legendFormat": "idle_size"
    }
   ]
  },
  {
   "title": "Increase of new connections by 15s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    increase(\n        asyncpg_connections_new_total{\n            deployment=\"$deployment\", \n            addr=\"$db_addr\",\n        }[15s]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}